CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS games (
  gameid INT AUTO_INCREMENT PRIMARY KEY,
  `user` INT NOT NULL,
  rounds INT NOT NULL,
  result ENUM('PLAYER_WON', 'COMPUTER_WON') NOT NULL,
  datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_games_user FOREIGN KEY (`user`) REFERENCES users(id)
);
